name: Python greeetings

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - name: Log message
        run: echo "Installing all pip dependencies..."
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: 'app'
      - name: Install deps step
        working-directory: app
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
  deploy-to-dev:
    runs-on: self-hosted
    needs : [ install-pip-deps ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mdaugavietis/python-app'
          sparse-checkout: .github/actions
          sparse-checkout-cone-mode: false
          path: python-app
      - uses: ./python-app/.github/actions/deploy
        with:
          env: 'dev'
          port: 7001
  tests-on-dev:
    runs-on: self-hosted
    needs : [ deploy-to-dev ]
    steps:
      - uses: ./python-app/.github/actions/test
        with:
          env: 'dev'

  deploy-to-staging:
    runs-on: self-hosted
    needs : [ tests-on-dev ]
    steps:
      - uses: ./python-app/.github/actions/deploy
        with:
          env: 'staging'
          port: 7002
  tests-on-staging:
    runs-on: self-hosted
    needs : [ deploy-to-staging ]
    steps:
      - uses: ./python-app/.github/actions/test
        with:
          env: 'staging'

  deploy-to-preprod:
    runs-on: self-hosted
    needs : [ tests-on-staging ]
    steps:
      - uses: ./python-app/.github/actions/deploy
        with:
          env: 'preprod'
          port: 7003
  tests-on-preprod:
    runs-on: self-hosted
    needs : [ deploy-to-preprod ]
    steps:
      - uses: ./python-app/.github/actions/test
        with:
          env: 'preprod'

  deploy-to-prod:
    runs-on: self-hosted
    needs : [ tests-on-preprod ]
    steps:
      - uses: ./python-app/.github/actions/deploy
        with:
          env: 'prod'
          port: 7004
  tests-on-prod:
    runs-on: self-hosted
    needs : [ deploy-to-prod ]
    steps:
      - uses: ./python-app/.github/actions/test
        with:
          env: 'prod'
