name: Python greeetings

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - name: Log message
        run: echo "Installing all pip dependencies..."
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: 'app'
      - name: Install deps step
        working-directory: app
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
  deploy-to-dev:
    runs-on: self-hosted
    needs : [ install-pip-deps ]
    steps:
      - name: Deploy the app to dev
        working-directory: app
        run: |
          source .venv/bin/activate
          RUNNER_TRACKING_ID="" && pm2 delete greetings-app-dev || true
          pm2 start app.py --name greetings-app-dev -- --port 7001
  tests-on-dev:
    runs-on: self-hosted
    needs : [ deploy-to-dev ]
    steps:
      - name: Log message
        run: echo "Placeholder"
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/course-js-api-framework'
          path: 'tests'
      - name: Setup and run tests on dev
        working-directory: tests
        run: |
          npm install
          npm run greetings greetings_dev

  deploy-to-staging:
    runs-on: self-hosted
    needs : [ tests-on-dev ]
    steps:
      - name: Log message
        run: echo "Placeholder"
  tests-on-staging:
    runs-on: self-hosted
    needs : [ deploy-to-staging ]
    steps:
      - name: Log message
        run: echo "Placeholder"
  deploy-to-preprod:
    runs-on: self-hosted
    needs : [ tests-on-staging ]
    steps:
      - name: Log message
        run: echo "Placeholder"
  tests-on-preprod:
    runs-on: self-hosted
    needs : [ deploy-to-preprod ]
    steps:
      - name: Log message
        run: echo "Placeholder"
  deploy-to-prod:
    runs-on: self-hosted
    needs : [ tests-on-preprod ]
    steps:
      - name: Log message
        run: echo "Placeholder"
  tests-on-prod:
    runs-on: self-hosted
    needs : [ deploy-to-prod ]
    steps:
      - name: Log message
        run: echo "Placeholder"
